### ISSUE TITLE
noise dimension reduction technique

### ISSUE THREAD

**Issue by thaoshibe** [poloclub/diffusion-explainer#1]
Hi,
Thank you for great works! It helps me to understand diffusion models better.

As far as I know, the noise is 512-dim. What's technique do you use to visualize these noises as a path?
![Screen Shot 2023-05-31 at 3 47 02 PM](https://github.com/poloclub/diffusion-explainer/assets/22058807/f1d901cf-fd4d-4489-8e5e-d5027df9fe5d)

Thank you!

**Comment by ligi214** [comment]
Hi, thanks for the question!

We used the UMAP visualization technique to project the noise (or noisy image representation) to the 2D space. You can see more details about the visualization of image representation and its path in our paper: https://arxiv.org/abs/2305.03509.
